// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWedkr0VI2is3d6LOaK82bE7iZ8xh5vw4',
    appId: '1:879008885552:web:97a3cad4df19c4cb6536f5',
    messagingSenderId: '879008885552',
    projectId: 'cinema-chat-82188',
    authDomain: 'cinema-chat-82188.firebaseapp.com',
    storageBucket: 'cinema-chat-82188.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOiv5w0dqWvsPqhZPQV8fLdbhoa8ZRAYQ',
    appId: '1:879008885552:android:ae4dd2e06036a3c56536f5',
    messagingSenderId: '879008885552',
    projectId: 'cinema-chat-82188',
    storageBucket: 'cinema-chat-82188.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3LiJSntFV9zhDJzT_jBoSMexEqWItBfM',
    appId: '1:879008885552:ios:45be8bc674ee3caf6536f5',
    messagingSenderId: '879008885552',
    projectId: 'cinema-chat-82188',
    storageBucket: 'cinema-chat-82188.firebasestorage.app',
    iosBundleId: 'com.example.cinemaChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3LiJSntFV9zhDJzT_jBoSMexEqWItBfM',
    appId: '1:879008885552:ios:45be8bc674ee3caf6536f5',
    messagingSenderId: '879008885552',
    projectId: 'cinema-chat-82188',
    storageBucket: 'cinema-chat-82188.firebasestorage.app',
    iosBundleId: 'com.example.cinemaChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWedkr0VI2is3d6LOaK82bE7iZ8xh5vw4',
    appId: '1:879008885552:web:2878ca96b0c7d67a6536f5',
    messagingSenderId: '879008885552',
    projectId: 'cinema-chat-82188',
    authDomain: 'cinema-chat-82188.firebaseapp.com',
    storageBucket: 'cinema-chat-82188.firebasestorage.app',
  );
}
